### ISSUE TITLE
Avatar list is not being displayed at times

### ISSUE THREAD

**Issue by mahadevans87** [Room4O4/pictionary#75]
![image](https://user-images.githubusercontent.com/1255523/96371854-81bc8080-1181-11eb-9100-69a5743e5d57.png)

**Comment by existentialcoder** [comment]
Is this still reproduceable?

**Comment by mahadevans87** [comment]
Yes. Actually the server crashed due to an issue with the paths of avatars being generated. This was fixed a couple of weeks ago. Thanks
